---
- hosts: asa
  gather_facts: false
  collections:
    - community.general
    - cisco.asa
  vars:
    ansible_network_os: cisco.asa.asa
    ansible_connection: ansible.netcommon.network_cli
    ansible_become: true
    ansible_become_method: enable

  tasks:
    - name: SHOW VERSION
      cisco.asa.asa_command:
        commands:
          - show version
      register: version

    - debug: var=version.stdout_lines

    - name: Gather facts
      cisco.asa.asa_facts:
        gather_subset: all
      register: asa_facts

    - name: configure ASA interface with standby
      cisco.asa.asa_config:
        lines:
          - description my cloud interface
          - nameif cloud13
          - security-level 50
          - ip address 10.10.10.1 255.255.255.0 standby 10.10.10.2
        parents: [interface GigabitEthernet0/1]
      register: interface
    - name: Show changes to interface from task above
      ansible.builtin.debug:
        var: interface

    - name: configurable backup path
      cisco.asa.asa_config:
        lines:
          - configure terminal
          - access-list global_access extended permit ip any any
          - access-group global_access global
        backup: true
        backup_options:
          filename: "{{ asa_facts.ansible_facts.ansible_net_hostname }}.cfg"
          dir_path: /tmp/semaphore/backup

    - name: save running to startup when modified
      cisco.asa.asa_config:
        save_when: modified

    - name: Save version output to file
      copy:
        content: "{{ version.stdout[0] }}"
        dest: "/tmp/semaphore/backup/asa_version_output.txt"

    - name: Save Gather output to file
      copy:
        content: "{{ asa_facts.stdout[0] }}"
        dest: "/tmp/semaphore/backup/asa_facts_output.txt"
