---
- hosts: asa
  gather_facts: false
  collections:
    - community.general
    - cisco.asa
  vars:
    ansible_network_os: cisco.asa.asa
    ansible_connection: ansible.netcommon.network_cli
    become: true
    become_method: enable

  tasks:
    - name: SHOW VERSION
      cisco.asa.asa_command:
        commands:
          - show version
      register: version

    - debug: var=version.stdout_lines
    - name: Save version output to file
      copy:
        content: "{{ version.stdout[0] }}"
        dest: "asa_version_output.txt"
